apiVersion: v1
data:
  01-init-mydonations-table.sql: "/* \n  Create the `mydonations` database.\n  Set up a starter table to work from.\n*/\nCREATE DATABASE IF NOT EXISTS `mydonations`;\nUSE `mydonations`;\n\n-- Create starter table `donation`\nDROP TABLE IF EXISTS `donation`;\nCREATE TABLE `donation` (\n    `id` int NOT NULL AUTO_INCREMENT,\n    `donor_name` varchar(255) NOT NULL,\n    `donor_email` varchar(255) NOT NULL,\n    `donor_comments` mediumtext,\n    `donation_currency` char(3) NOT NULL,\n    `donation_amount` decimal(10,2) NOT NULL,\n    `transaction_id` varchar(255) NOT NULL,\n    `transaction_mode` varchar(255) NOT NULL,\n    `transaction_status` varchar(255) NOT NULL,\n    `request` longtext NOT NULL,\n    `response` longtext NOT NULL,\n    `created_at` datetime DEFAULT CURRENT_TIMESTAMP,\n    PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;\n"
kind: ConfigMap
metadata:
  labels:
    app.mydonations: mysql
  name: mysql-configmap
